services:
  - type: web
    name: minecraft-gang-dashboard
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: PANEL_URL
        value: https://panel.skilloraclouds.com
      - key: API_KEY
        value: ptlc_LPQgGvrbQdE
      - key: SERVER_ID
        value: ""
